import { Theme } from "../../theme.slint";
import { Store } from "../../store.slint";
import { IconBtn } from "../../base/icon-btn.slint";
import { Avatar } from "../../base/avatar.slint";
import { Logic } from "../../logic.slint";

export component BItem inherits VerticalLayout{
    in-out property<string> uuid;
    in-out property<int> index;
    in-out property<image> img;

    padding-left: Theme.scroll-width;
    spacing: Theme.spacing;

    HorizontalLayout {
        padding-bottom: Theme.padding;
        alignment: space-between;

        HorizontalLayout {
            padding-left: Theme.padding;
            spacing: Theme.spacing * 2;

            VerticalLayout {
                alignment: center;
                IconBtn {
                    icon: @image-url("../../images/save-light.svg");
                    tip-text: Store.translator.tip-save;
                    clicked => {
                        Logic.save-chat-image(root.uuid, root.index);
                    }
                }
            }
        }

        Avatar {
            icon-source: @image-url("../../images/bot.svg");
        }
    }

    VerticalLayout {
        spacing: Theme.spacing * 4;

        Rectangle {
            background: Theme.dark-fill-color;
            border-radius: Theme.border-radius;

            Image {
                width: parent.width;
                source: root.img;
            }
        }
    }
}

