import { Theme } from "../../theme.slint";
import { Store } from "../../store.slint";
import { Logic } from "../../logic.slint";
import { Name } from "./name.slint";
import { Display } from "./display.slint";

export component Font inherits Rectangle {
    HorizontalLayout {
        spacing: Theme.spacing;
        display := Display {
           font-name: name.font-name;
           font-family: name.font-family;
        }

        name := Name {
            selected => {
                display.scoll-to-top();
            }
        }
    }
}
