import { Theme } from "./theme.slint";
import { Logic } from "./logic.slint";
import { Util } from "./util.slint";
import { Store, ColorItem, FontItem, ColorPickerConfig, ColorMakerConfig } from "./store.slint";
import { Side } from "./side/panel.slint";
import { Body } from "./body/panel.slint";
import { Message } from "./base/message.slint";
import { About } from "./dialog/about.slint";
import { Help } from "./dialog/help.slint";
import { Setting } from "./dialog/setting/dialog.slint";

export component AppWindow inherits Window {
    width: Theme.default-width;
    height: Theme.default-height + Theme.padding;
    background: Theme.base-background;
    default-font-size: Theme.default-font-size;
    default-font-family: Theme.default-font-family;
    forward-focus: fscope;
    no-frame: true;
    title: "uibox";

    fscope := FocusScope {
        property <bool> is-ctrl-pressed: false;
        key-pressed(event) => {
            if (event.text == Key.Control) {
                is-ctrl-pressed = true;
            } else if (event.text == Key.Escape) {
                modal.hide();
            }

            if (is-ctrl-pressed) { }
            accept
        }

        key-released(event) => {
            if (event.text == Key.Control) {
                is-ctrl-pressed = false;
            }
            accept
        }

        HorizontalLayout {
            padding: Theme.padding / 2;
            Rectangle {
                side := Side {
                    x: 0px;
                    z: 1;
                    selected-icon(name) => {
                        Store.selected-panel = name;
                    }
                }

                body := Body {
                    x: Theme.side-width;
                    z: 0;
                    width: Theme.body-width;
                }
            }
        }

        modal := Rectangle {
            function hide() {
                if (about-dialog.visible) {
                    Store.about-dialog.show = false;
                } else if (help-dialog.visible) {
                    Store.help-dialog.show = false;
                } else if (setting-dialog.visible) {
                    Store.setting-dialog.show = false;
                }
            }

            if about-dialog.visible || help-dialog.visible || setting-dialog.visible: Rectangle {
                width: 100%; height: 100%; opacity: 0.3;
                background: Theme.basic-black-color;
                TouchArea { }
            }

            about-dialog := About { }
            help-dialog :=  Help { }
            setting-dialog :=  Setting { }
        }

        Message {
            x: root.width / 2 - self.width / 2;
            y: 50px;
            text: Store.message.text;
            type: Store.message.text-type;
            clicked => {
                Logic.copy-to-clipboard(self.text);
            }
        }
    }
}

export { Util, Logic, Store, ColorItem, FontItem, ColorPickerConfig, ColorMakerConfig }
