import { SettingDialogConfig } from "./store.slint";
import { ColorPickerConfig, ColorMakerConfig } from "./store.slint";

export global Logic {
    callback handle-ok-cancel-dialog(string, string);
    callback copy-to-clipboard(string);
    callback show-message(string, string);

    callback setting-cancel();
    callback setting-ok(SettingDialogConfig);

    callback search-font(string);

    callback load-image() -> image;
    load-image() => {
        return  @image-url("./images/robot.svg");
    }

    callback image-point-color(float, float) -> ColorPickerConfig;

    callback delete-chat-item(string);
    callback send-question-text(string);
    callback save-chat-image(string, int);
    callback clean-image-cache();

    pure callback current-display-color(float, float, color) -> ColorMakerConfig;
    pure callback current-color-band-color(float, float) -> color;
    pure callback hex-value(int, int, int) -> string;
}

