import { SettingDialogConfig } from "./store.slint";
import { ColorPickerConfig } from "./store.slint";

export global Logic {
    callback copy-to-clipboard(string);
    callback show-message(string, string);

    callback setting-cancel();
    callback setting-ok(SettingDialogConfig);

    callback search-font(string);

    callback load-image() -> image;
    load-image() => {
        return  @image-url("./images/robot.svg");
    }

    callback image-point-color(float, float) -> ColorPickerConfig;

    pure callback current-color-band-color(float, float) -> color;
    pure callback hex-value(int, int, int) -> string;
}

