import { Translator, Translation} from "./translator.slint";

export enum SelectPanel { colorpalette, colormaker, colorpicker, systemfont }

export struct ColorItem {
    name: string,
    hex: string,
    value: color,
}

export struct MessageItem {
    text: string,
    text-type: string,
}

export struct AboutDialog {
    show: bool,
    title: string,
    text: string,
    sponsor: string,
}

export struct SettingUI {
    font-size: string,
    font-family: string,
    win-width: string,
    win-height: string,
    language: string,
}

export struct SettingDialogConfig {
    show: bool,
    ui: SettingUI,
}

export struct FontItem {
    postscript-name: string,
    name: string,
    family: string,
    styles: [string],
    weight: float,
    stretch: float,
}

export struct ColorPickerConfig {
    red: int,
    green: int,
    blue: int,
    alpha: int,
    hex: string,
}

export global Store  {
    in-out property<MessageItem> message;

    in-out property<[ColorItem]> colors: [
        {
            name: "red",
            value: rgb(255, 0, 0),
        },
        {

            name: "green",
            value: rgb(0, 255, 0),
        },
        {
            name: "blue",
            value: rgb(0, 0, 255),
        },
    ];


    in-out property<[FontItem]> fonts-cache: [];
    in-out property<[FontItem]> fonts: [
        {
            postscript-name: "monospacefjwifjwifjwijweifjweif",
            name: "adobel monospace",
            family: "adobel",
            styles: ["Normal", "Italic"],
            weight: 400.0,
            stretch: 0.8,
        }
    ];

    in-out property<SettingDialogConfig> setting-dialog: {
        show: false,
        ui: {
            font-size: "20",
            font-family: "SourceHanSerifCN",
            language: "cn",
        }
    };

    in-out property<Translation> translator: Translator.translation(setting-dialog.ui.language == "cn");

    in-out property<AboutDialog> about-dialog: {
        show: false,
        title: "uibox v1.0.0",
        text: "Based on Slint-UI. Copyright 2022-2030 The Heng30 Company Ltd. All rights reserved. The program is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.",
        sponsor: "0xf1199999751b1a3A74590adBf95401D19AB30014",
    };

    in-out property<{show: bool, text-cn: string, text-en: string}> help-dialog: {
        show: false,
        text-cn:
            "调色板:\n"
            + "  1. 颜色格式：RGBA。\n",
        text-en:
            "Color Palette:\n"
            + "  1. Color Format: RGBA.\n",
    };
}

