import { Translator, Translation} from "./translator.slint";

export enum SelectPanel { colors, setting }

export struct ColorItem {
    name: string,
    value: color,
}

export struct MessageItem {
    text: string,
    text-type: string,
}

export global Store  {
    in-out property<MessageItem> message;

    in-out property<[ColorItem]> colors: [
        {
            name: "red",
            value: rgb(255, 0, 0),
        },
        {

            name: "green",
            value: rgb(0, 255, 0),
        },
        {
            name: "blue",
            value: rgb(0, 0, 255),
        },
    ];
}

