export struct Translation {
    cancel: string,
    ok: string,

    warning: string,
    setting: string,
    help: string,
    about: string,

    delete-or-not: string,
    enter-to-send: string,

    setting-dialog-ui: string,
    setting-dialog-ui-font-size: string,
    setting-dialog-ui-font-family: string,
    setting-dialog-ui-language: string,

    setting-dialog-image-gen: string,
    setting-dialog-image-gen-size: string,
    setting-dialog-image-gen-count: string,
    setting-dialog-image-gen-cache-clean: string,

    setting-dialog-proxy: string,
    setting-dialog-proxy-openai-disabled: string,
    setting-dialog-proxy-openai-enabled: string,
    setting-dialog-proxy-url: string,
    setting-dialog-proxy-url-placeholder: string,
    setting-dialog-proxy-port: string,
    setting-dialog-proxy-port-placeholder: string,

    no-data: string,
    search-placeholder: string,

    system-default-font: string,

    red: string,
    green: string,
    blue: string,
    alpha: string,
    hex: string,

    tip-min: string,
    tip-max: string,
    tip-delete: string,
    tip-copy: string,
    tip-save: string,
    tip-createimg: string,
    tip-colorpalette: string,
    tip-colormaker: string,
    tip-colorpicker: string,
    tip-systemfont: string,
    tip-setting: string,
    tip-help: string,
    tip-about: string,
    tip-pick-color: string,
    tip-zoom-in: string,
    tip-zoom-out: string,
    tip-zoom-recover: string,
    tip-remove-image: string,
    tip-load-img: string,
    tip-retry: string,
}

export global Translator {
    public pure function translation(is-cn: bool) -> Translation {
        return {
            cancel: is-cn ? "取消" : "Cancel",
            ok: is-cn ? "确定" : "Confirm",

            warning: is-cn ? "警  告" : "Warning",
            setting: is-cn ? "设  置" : "Setting",
            help: is-cn ? "帮  助" : "Help",
            about: is-cn ? "关  于" : "About",

            delete-or-not: is-cn ? "是否删除?" : "Delete or not?",
            enter-to-send: is-cn ? "按回车发送" : "Enter to send",

            setting-dialog-ui: is-cn ? "界面" : "UI",
            setting-dialog-ui-font-size: is-cn ? "字体大小:" : "Font Size:",
            setting-dialog-ui-font-family: is-cn ? "字体样式:" : "Font Family:",
            setting-dialog-ui-language: is-cn ? "选择语言:" : "Language:",


            setting-dialog-image-gen: is-cn ? "会话" : "Chat",
            setting-dialog-image-gen-size: is-cn ? "图片大小:" : "Image Size:",
            setting-dialog-image-gen-count: is-cn ? "图片数量:" : "Image Count:",
            setting-dialog-image-gen-cache-clean: is-cn ? "清除图片缓存" : "clean image cache",


            setting-dialog-proxy: is-cn ? "代理": "Proxy",
            setting-dialog-proxy-openai-disabled: is-cn ? "OpenAI未启用代理" : "Disabled OpenAI Proxy",
            setting-dialog-proxy-openai-enabled: is-cn ? "OpenAI已启用代理" : "Enabled OpenAI Proxy",
            setting-dialog-proxy-url-placeholder: is-cn ? "请输入URL/IP:" : "URL/IP",
            setting-dialog-proxy-port: is-cn ? "端口:" : "Port:",
            setting-dialog-proxy-port-placeholder: is-cn ? "请输入端口" : "Port",

            no-data: is-cn ? "没有数据" : "No Data",
            search-placeholder: is-cn ? "请输入关键字" : "Input Keywords",

            system-default-font: is-cn ? "系统默认字体" : "System Default Font",

            red: is-cn ? "红通道:" : "Red:",
            green: is-cn ? "绿通道:" : "Green:",
            blue: is-cn ? "蓝通道:" : "Blue:",
            alpha: is-cn ? "透明度:" : "Alpha:",
            hex: is-cn ? "颜色值:" : "Color:",

            tip-min: is-cn ? "缩小" : "Zoom Out",
            tip-max: is-cn ? "放大" : "Zoom In",
            tip-delete: is-cn ? "删除" : "Delete",
            tip-copy: is-cn ? "复制" : "Copy",
            tip-save: is-cn ? "保存" : "Save",
            tip-createimg: is-cn ? "创建图片" : "Create Image",
            tip-colorpalette: is-cn ? "颜色板" : "Color Palette",
            tip-colormaker: is-cn ? "调色板" : "Color Maker",
            tip-colorpicker: is-cn ? "取色器" : "Color Picker",
            tip-systemfont: is-cn ? "系统字体" : "System Font",
            tip-setting: is-cn ? "设置" : "Setting",
            tip-help: is-cn ? "帮助" : "Help",
            tip-about: is-cn ? "关于" : "About",
            tip-pick-color: is-cn ? "取色" : "Pick Color",
            tip-zoom-in: is-cn ? "缩小" : "Zoom In",
            tip-zoom-out: is-cn ? "放大" : "Zoom Out",
            tip-zoom-recover: is-cn ? "恢复大小" : "Reset Size",
            tip-remove-image: is-cn ? "移除图片": "Romove Image",
            tip-load-img: is-cn ? "点击加载图片" : "Click to Load Image",
            tip-retry: is-cn ? "重新生成" : "Retry",
        };
    }
}
