import { Theme } from "../theme.slint";
import { Store, SelectPanel } from "../store.slint";
import { Colors } from "./colors.slint";

export component Body inherits VerticalLayout {
    in-out property<SelectPanel> selected-panel: SelectPanel.colors;

    colors-panel := Colors {
        visible: selected-panel == SelectPanel.colors;
        height: self.visible ? Theme.default-height : 0px;
    }
}
