import { Theme } from "../../theme.slint";
import { Store } from "../../store.slint";
import { Logic } from "../../logic.slint";
import { Btn } from "../../base/btn.slint";
import { Divider } from "../../base/divider.slint";
import { TabBtn } from "../../base/tab-btn.slint";
import { UI } from "./ui.slint";
import { CDialog } from "../../base/cdialog.slint";

export component Setting inherits CDialog {
    property<string> current-checked-item: "ui";

    callback close();

    visible: Store.setting-dialog.show;
    title: Store.translator.setting;

    VerticalLayout {
        alignment: start;
        height: Theme.default-height * 0.618;

        VerticalLayout {
            spacing: Theme.spacing * 2;
            padding: Theme.padding * 2;
            padding-bottom: Theme.padding * 10;

            // HorizontalLayout {
            //     alignment: space-around;
            //     height: Theme.default-font-size + Theme.padding * 2;

            //     TabBtn {
            //         text: Store.translator.setting-dialog-ui;
            //         icon: @image-url("../../images/setting-fill.svg");
            //         checked: current-checked-item == "ui";
            //         clicked => {
            //             current-checked-item = "ui";
            //         }
            //     }
            // }

            // HorizontalLayout {
            //     alignment: center;
            //     Divider {
            //         width: 100%;
            //     }
            // }

            Rectangle {
                ui-tab := UI {
                    visible: current-checked-item == "ui";
                    font-size: Theme.default-font-size / 1px;
                    font-family: Store.setting-dialog.ui.font-family;
                }
            }
        }

    }

    cancel-clicked => {
        Logic.setting-cancel();

        ui-tab.font-size = Theme.default-font-size / 1px;
        ui-tab.font-family = Store.setting-dialog.ui.font-family;
        ui-tab.set-language(Store.setting-dialog.ui.language);

        Store.setting-dialog.show = false;
        root.close();
    }

    ok-clicked => {
        Logic.setting-ok({
            ui: {
                font-size: ui-tab.font-size,
                font-family: ui-tab.font-family,
                language: ui-tab.language
            },
        });

        Store.setting-dialog.show = false;
        root.close();
    }
}
