import { CheckBox, LineEdit, ComboBox } from "std-widgets.slint";
import { Theme } from "../../theme.slint";
import { Store } from "../../store.slint";
import { Logic } from "../../logic.slint";
import { Label } from "../../base/label.slint";
import { Btn } from "../../base/btn.slint";

export component ImageGen inherits Rectangle {
    property<length> label-width: Theme.default-label-width;

    in-out property api-key <=> api-lineedit.text;
    in-out property api-base <=> url-lineedit.text;
    in-out property image-count <=> count-combox.current-value;
    in-out property image-size <=> size-combox.current-value;

    VerticalLayout {
        spacing: Theme.spacing * 4;
        alignment: start;

        HorizontalLayout {
            api-txt := Label {
                width: label-width;
                text: "API Key:";
            }

            api-lineedit := LineEdit {
                placeholder-text: "API Key";
                input-type: self.has-focus ? text : password;
            }
        }

        HorizontalLayout {
            url-txt := Label {
                width: label-width;
                text: "API Base:";
            }

            url-lineedit := LineEdit {
                placeholder-text: "API Base";
            }
        }

        HorizontalLayout {
            size-txt := Label {
                width: label-width;
                text: Store.translator.setting-dialog-image-gen-size;
            }

            size-combox := ComboBox {
                model: ["256x256", "512x512", "1024x1024"];
                current-value: self.model[0];
                current-index: 0;
            }
        }

        HorizontalLayout {
            count-txt := Label {
                width: label-width;
                text: Store.translator.setting-dialog-image-gen-count;
            }

            count-combox := ComboBox {
                model: [1, 2, 3, 4, 5];
                current-value: self.model[0];
                current-index: 0;
            }
        }

        Btn {
            bg-color: Theme.danger-color;
            border-radius: Theme.border-radius;
            text: Store.translator.setting-dialog-image-gen-cache-clean + "(" + Store.setting-dialog.chat.cache-size + ")";
            icon: @image-url("../../images/warning.svg");
            clicked => {
                Logic.clean-image-cache();
            }
        }

    }
}
