import { Theme } from "../theme.slint";
import { Store } from "../store.slint";
import { SelectPanel } from "../store.slint";
import { IconBtn } from "../base/icon-btn.slint";
import { CenterLayout } from "../base/center-layout.slint";
import { Divider } from "../base/divider.slint";

export component Side inherits Rectangle {
    width: Theme.side-width;
    background: Theme.darker-fill-color;

    callback selected-icon(SelectPanel);

    HorizontalLayout {
        VerticalLayout {
            alignment: space-between;
            padding-top: Theme.padding;
            padding-bottom: Theme.padding;
            spacing: Theme.spacing * 3;

            VerticalLayout {
                spacing: Theme.spacing * 2;

                CenterLayout {
                    IconBtn {
                        width: root.width * 0.7;
                        icon-width: self.width * 0.8;
                        icon: @image-url("../images/picture.svg");
                        bg-color: Theme.hover-color.darker(10%);
                        hover-color: Theme.hover-color.darker(30%);
                        colorize: Theme.primary-text-color;
                        tip-pos: "right";
                        tip-text: Store.translator.tip-colorpicker;
                        checked: Store.selected-panel == SelectPanel.colorpicker;

                        clicked => {
                            root.selected-icon(SelectPanel.colorpicker);
                        }
                    }
                }

                CenterLayout {
                    IconBtn {
                        width: root.width * 0.7;
                        icon-width: self.width * 0.8;
                        icon: @image-url("../images/colorplate.svg");
                        bg-color: Theme.hover-color.darker(10%);
                        hover-color: Theme.hover-color.darker(30%);
                        colorize: Theme.primary-text-color;
                        tip-pos: "right";
                        tip-text: Store.translator.tip-colorpalette;
                        checked: Store.selected-panel == SelectPanel.colorpalette;

                        clicked => {
                            root.selected-icon(SelectPanel.colorpalette);
                        }
                    }
                }

                CenterLayout {
                    IconBtn {
                        width: root.width * 0.7;
                        icon-width: self.width * 0.8;
                        icon: @image-url("../images/colormaker.svg");
                        bg-color: Theme.hover-color.darker(10%);
                        hover-color: Theme.hover-color.darker(30%);
                        colorize: Theme.primary-text-color;
                        tip-pos: "right";
                        tip-text: Store.translator.tip-colormaker;
                        checked: Store.selected-panel == SelectPanel.colormaker;

                        clicked => {
                            root.selected-icon(SelectPanel.colormaker);
                        }
                    }
                }

                CenterLayout {
                    IconBtn {
                        width: root.width * 0.7;
                        icon-width: self.width * 0.8;
                        icon: @image-url("../images/font.svg");
                        bg-color: Theme.hover-color.darker(10%);
                        hover-color: Theme.hover-color.darker(30%);
                        colorize: Theme.primary-text-color;
                        tip-pos: "right";
                        tip-text: Store.translator.tip-systemfont;
                        checked: Store.selected-panel == SelectPanel.systemfont;

                        clicked => {
                            root.selected-icon(SelectPanel.systemfont);
                        }
                    }
                }
            }

            VerticalLayout {
                spacing: Theme.spacing * 2;

                CenterLayout {
                    IconBtn {
                        width: root.width * 0.7;
                        icon-width: self.width * 0.8;
                        icon: @image-url("../images/setting-fill.svg");
                        bg-color: Theme.hover-color.darker(10%);
                        hover-color: Theme.hover-color.darker(30%);
                        colorize: Theme.primary-text-color;
                        tip-pos: "right";
                        tip-text: Store.translator.tip-setting;

                        clicked => {
                            Store.setting-dialog.show = true;
                        }
                    }
                }

                CenterLayout {
                    IconBtn {
                        width: root.width * 0.7;
                        icon-width: self.width * 0.8;
                        icon: @image-url("../images/help.svg");
                        bg-color: Theme.hover-color.darker(10%);
                        hover-color: Theme.hover-color.darker(30%);
                        colorize: Theme.primary-text-color;
                        tip-pos: "right";
                        tip-text: Store.translator.tip-help;

                        clicked => {
                            Store.help-dialog.show = true;
                        }
                    }
                }

                CenterLayout {
                    IconBtn {
                        width: root.width * 0.7;
                        icon-width: self.width * 0.8;
                        icon: @image-url("../images/info-dark.svg");
                        bg-color: Theme.hover-color.darker(10%);
                        hover-color: Theme.hover-color.darker(30%);
                        colorize: Theme.primary-text-color;
                        tip-pos: "right";
                        tip-text: Store.translator.tip-about;

                        clicked => {
                            Store.about-dialog.show = true;
                        }
                    }
                }
            }
        }

        Divider {
            width: 1px;
            height: root.height;
            background: Theme.light-border-color;
        }
   }
}
