import { Theme } from "../theme.slint";
import { Store } from "../store.slint";
import { SelectPanel } from "../store.slint";
import { IconBtn } from "../base/icon-btn.slint";
import { CenterLayout } from "../base/center-layout.slint";
import { Divider } from "../base/divider.slint";

export component Side inherits Rectangle {
    width: Theme.side-width;
    background: Theme.darker-fill-color;

    callback selected-icon(SelectPanel);

    HorizontalLayout {
        VerticalLayout {
            alignment: space-between;
            padding-top: Theme.padding;
            padding-bottom: Theme.padding;
            spacing: Theme.spacing * 3;

            CenterLayout {
                IconBtn {
                    width: root.width * 0.8;
                    icon-width: self.width * 0.8;
                    icon: @image-url("../images/colorplate.svg");
                    bg-color: Theme.hover-color.darker(10%);
                    hover-color: Theme.hover-color.darker(30%);
                    tip-pos: "right";
                    tip-text: Store.translator.tip-colorplate;

                    clicked => {
                        root.selected-icon(SelectPanel.colors);
                    }
                }
            }

            VerticalLayout {
                spacing: Theme.spacing * 3;

                CenterLayout {
                    IconBtn {
                        width: root.width * 0.8;
                        icon-width: self.width * 0.8;
                        icon: @image-url("../images/setting-fill.svg");
                        bg-color: Theme.hover-color.darker(10%);
                        hover-color: Theme.hover-color.darker(30%);
                        tip-pos: "right";
                        tip-text: Store.translator.tip-setting;

                        clicked => {
                            root.selected-icon(SelectPanel.setting);
                        }
                    }
                }

                CenterLayout {
                    IconBtn {
                        width: root.width * 0.8;
                        icon-width: self.width * 0.8;
                        icon: @image-url("../images/help.svg");
                        bg-color: Theme.hover-color.darker(10%);
                        hover-color: Theme.hover-color.darker(30%);
                        tip-pos: "right";
                        tip-text: Store.translator.tip-help;

                        clicked => {
                            root.selected-icon(SelectPanel.help);
                        }
                    }
                }

                CenterLayout {
                    IconBtn {
                        width: root.width * 0.8;
                        icon-width: self.width * 0.8;
                        icon: @image-url("../images/about.svg");
                        bg-color: Theme.hover-color.darker(10%);
                        hover-color: Theme.hover-color.darker(30%);
                        tip-pos: "right";
                        tip-text: Store.translator.tip-about;

                        clicked => {
                            Store.about-dialog.show = true;
                        }
                    }
                }
            }
        }

        Divider {
            width: 1px;
            height: root.height;
            background: Theme.light-border-color;
        }
   }
}
